version: '2.2'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JUPYTER_ENABLE_LAB: 1
      HOME: /home/jovyan/${PROJECT_NAME}
    ports:
      - 8888:8888
    volumes:
      - ../:/home/jovyan/${PROJECT_NAME}
    command: start-notebook.sh --NotebookApp.token=''
